name: Convert Logs → Build ELN → Deploy to Pages

on:
  push:
    paths:
      - 'notebooks/**/*.md'
      - 'intro.md'
      - '_config.yml'
      - '_static/**'
      - '.github/workflows/deploy-book.yml'

jobs:
  deploy-eln:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Convert .md to .ipynb only if needed
        run: |
          mkdir -p converted
          for file in notebooks/*.md; do
            base=$(basename "$file" .md)
            ipynb="converted/${base}.ipynb"
            if [ ! -f "$ipynb" ] || [ "$file" -nt "$ipynb" ]; then
              echo "Converting $file → $ipynb"
              jupytext --to ipynb "$file" -o "$ipynb"
            else
              echo "Skipping $file (already up-to-date)"
            fi
          done

      - name: Auto-generate _toc.yml
        run: |
          echo "format: jb-book" > _toc.yml
          echo "root: intro" >> _toc.yml
          echo "chapters:" >> _toc.yml
          for file in $(ls notebooks/*.md | sort); do
            base=$(basename "$file" .md)
            echo "  - file: notebooks/$base" >> _toc.yml
          done

      - name: Build Jupyter Book
        run: jupyter-book build .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
