name: Auto-upload ELN to OSF

on:
  push:
    paths:
      - 'notebooks/**/*.md'
      - 'converted/**/*.ipynb'

jobs:
  upload-to-osf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install osfclient
        run: pip install osfclient

      - name: Configure OSF CLI
        run: |
          mkdir -p ~/.osfclient
          echo "[osf]" > ~/.osfcli.config
          echo "token = ${{ secrets.OSF_TOKEN }}" >> ~/.osfcli.config

      - name: Upload .md and .ipynb to OSF
        run: python osf_upload.py
        env:
          OSF_PROJECT_ID: ${{ secrets.OSF_PROJECT_ID }}
